# Generated by Django 5.2.5 on 2026-01-29 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='sendcompalint',
            new_name='sendcomplaint',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='place',
            new_name='status',
        ),
    ]
