# Generated by Django 5.2.5 on 2026-01-30 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_sendcompalint_complaint_sendcomplaint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='status',
        ),
    ]
