# Generated by Django 5.2.5 on 2026-01-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_users_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=100)),
                ('case_title', models.CharField(max_length=100)),
                ('case_type', models.CharField(max_length=100)),
                ('date_of_incident', models.DateField()),
                ('case_description', models.CharField(max_length=200)),
                ('date_filed', models.DateField()),
                ('petitioner_name', models.CharField(max_length=100)),
                ('petitioner_email', models.CharField(max_length=100)),
                ('petitioner_phone', models.CharField(max_length=100)),
                ('petitioner_place', models.CharField(max_length=100)),
                ('petitioner_pincode', models.CharField(max_length=100)),
                ('petitioner_district', models.CharField(max_length=100)),
                ('petitioner_state', models.CharField(max_length=100)),
                ('accused', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('filing_mode', models.CharField(max_length=100)),
                ('court_name', models.CharField(max_length=100)),
                ('judge_assigned', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('case_duration_days', models.CharField(max_length=100)),
            ],
        ),
    ]
